### ISSUE TITLE
Error with negative rolls with modifiers

### ISSUE THREAD

**Issue by Wiadomy** [borntyping/python-dice#20]
Hello! I have weird error:

> dice.roll("(-1d20+4)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/dice/__init__.py", line 24, in roll
    return _roll(string, **kwargs)
  File "/usr/lib/python3.6/site-packages/dice/__init__.py", line 48, in _roll
    for element in elements]
  File "/usr/lib/python3.6/site-packages/dice/__init__.py", line 48, in <listcomp>
    for element in elements]
  File "/usr/lib/python3.6/site-packages/dice/elements.py", line 65, in evaluate_cached
    self.result = self.evaluate(cache=True, **kwargs)
  File "/usr/lib/python3.6/site-packages/dice/elements.py", line 379, in evaluate
    self.operands = self.preprocess_operands(*self.operands, **kwargs)
  File "/usr/lib/python3.6/site-packages/dice/elements.py", line 415, in preprocess_operands
    return [eval_wrapper(o) for o in operands]
  File "/usr/lib/python3.6/site-packages/dice/elements.py", line 415, in <listcomp>
    return [eval_wrapper(o) for o in operands]
  File "/usr/lib/python3.6/site-packages/dice/elements.py", line 413, in eval_wrapper
    return self.evaluate_object(operand, Integer, **kwargs)
  File "/usr/lib/python3.6/site-packages/dice/elements.py", line 54, in evaluate_object
    obj = cls(obj)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

However, `-1d20`  or `1d20+4` works. Why?

**Comment by calebj** [comment]
Looks like an bug with the Negate operator. Will look into it ASAP.
