### ISSUE TITLE
Possible to roll a negative number

### ISSUE THREAD

**Issue by bbriggs** [borntyping/python-dice#9]
I have wrapped this library using [legos.dice](https://pypi.python.org/pypi/legos.dice) for use in a chatbot. In my module, we merely grab the roll value and pass it straight to a call do `dice`. 

One of my users just discovered this fun bug:

```
│“19:11”                              ⤷ ╡ !roll -1d42                                                                                                                   │
│“19:11”                MissMoneyPenney ╡ You Rolled: -29
```

**Comment by borntyping** [comment]
Hmm. This is neat, though I'm not sure it's actually a bug - is there other behaviour you'd expect?

**Comment by bbriggs** [comment]
Well, I wouldn't expect to be able to roll a negative number (or have a negative number caused by a negative value for dice). These should all be natural numbers, right?

**Comment by bbriggs** [comment]
Maybe a solution here would be to check the input numbers against `abs(input)`?

**Comment by borntyping** [comment]
I think - but I'm not certain - this is getting parsed as `-(1d42)` (it's been a while since I last wrote any code for this). Could you run this in verbose mode and comment with the output?

**Comment by bbriggs** [comment]
Didn't end well trying this in just bash:
```
bren at Brens-MacBook-Pro.local in ~ on master*
$ virtualenv -p `which python3` ~/.venv/dice-3
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/bren/.venv/dice-3/bin/python3.6
Also creating executable in /Users/bren/.venv/dice-3/bin/python
Installing setuptools, pip, wheel...done.
bren at Brens-MacBook-Pro.local in ~ on master*
$ pip install dice
Collecting dice
  Using cached dice-1.1.0-py2.py3-none-any.whl
Collecting docopt>=0.6.1 (from dice)
Collecting pyparsing>=2.0.1 (from dice)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Installing collected packages: docopt, pyparsing, dice
Successfully installed dice-1.1.0 docopt-0.6.2 pyparsing-2.2.0
You have new mail in /var/mail/bren
bren at Brens-MacBook-Pro.local in ~ on master*
$ source ~/.venv/dice-3/bin/activate
(dice-3) bren at Brens-MacBook-Pro.local in ~ on master*
$ roll --verbose -1d42
Usage:
    roll [--verbose] <expression>
(dice-3) bren at Brens-MacBook-Pro.local in ~ on master*
$ roll --verbose 1d-42
Traceback (most recent call last):
  File "/usr/local/bin/roll", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/dice/command.py", line 23, in main
    result = dice.roll(args['<expression>'], verbose=args['--verbose'])
  File "/usr/local/lib/python2.7/site-packages/dice/__init__.py", line 18, in roll
    ast = dice.grammar.expression.parseString(string, parseAll=True)
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
pyparsing.ParseException: Expected end of text (at char 1), (line:1, col:2)
(dice-3) bren at Brens-MacBook-Pro.local in ~ on master*
$ roll --verbose -(1d42)
-bash: syntax error near unexpected token `('
(dice-3) bren at Brens-MacBook-Pro.local in ~ on master*
$ roll --verbose "-(1d42)"
Usage:
    roll [--verbose] <expression>
(dice-3) bren at Brens-MacBook-Pro.local in ~ on master*
$
```

**Comment by bbriggs** [comment]
It was much happier doing it this way:
```
>>> dice.roll('-(1d42)', verbose=True)
Evaluating: 1d42 -> [31]
Evaluating: AddEvenSubOdd(1d42) -> -31
-31
>>>
```

**Comment by borntyping** [comment]
So that actually is a bug - the addevensubodd operator matches `-n` as well as `+-n`, as it uses `Word` instead of `Literal` (https://github.com/borntyping/python-dice/blob/db9864bc8c10b1c033dcd2959b928898db33a6a7/dice/grammar.py#L93).

**Comment by bbriggs** [comment]
I know absolutely nothing about this grammar parser but it looks interesting. Mind if I give patching this a shot?

**Comment by borntyping** [comment]
Please do! I've limited time to work on projects like this at the moment, so any contributions are really appreciated.
